version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.10
    commands:
      - echo Installing dependencies...
      - pip install -r requirements.txt
  build:
    commands:
      - echo Build phase: No actual build needed
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - app.py
    - requirements.txt
    - Dockerfile
    - buildspec.yml